# Generated by Django 2.0 on 2020-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200916_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='abstract',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='作者简介'),
        ),
        migrations.AddField(
            model_name='entry',
            name='books_author',
            field=models.CharField(max_length=128, null=True, verbose_name='PDF电子书作者'),
        ),
        migrations.AddField(
            model_name='entry',
            name='publish',
            field=models.CharField(max_length=200, null=True, verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='entry',
            name='publish_year',
            field=models.CharField(max_length=300, null=True, verbose_name='出版年'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(verbose_name='内容简介'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='book_imge',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='书籍配图'),
        ),
    ]
